In [1]:
import hoomd
import numpy
import hoomd.md
import sys
import gsd
import gsd.hoomd
hoomd.context.initialize("")

HOOMD-blue 2.3.3 DOUBLE HPMC_MIXED TBB SSE SSE2 
Compiled: 07/04/2018
Copyright 2009-2018 The Regents of the University of Michigan.
-----
You are using HOOMD-blue. Please cite the following:
* J A Anderson, C D Lorenz, and A Travesset. "General purpose molecular dynamics
  simulations fully implemented on graphics processing units", Journal of
  Computational Physics 227 (2008) 5342--5359
* J Glaser, T D Nguyen, J A Anderson, P Liu, F Spiga, J A Millan, D C Morse, and
  S C Glotzer. "Strong scaling of general-purpose molecular dynamics simulations
  on GPUs", Computer Physics Communications 192 (2015) 97--107
-----
HOOMD-blue is running on the CPU


In [2]:
import mbuild as mb
box = mb.load("/home/themotivation/Avo_atoms/airHCN.pdb")
box.save("/home/themotivation/Avo_atoms/airHCN.gsd")
print("it worked!")

OSError: /home/themotivation/Avo_atoms/airHCN.gsd exists; not overwriting

In [2]:
system = hoomd.init.read_gsd("/home/themotivation/Avo_atoms/airHCN.gsd")

notice(2): Group "all" created containing 19904 particles


In [3]:
#first line opens the gsd file so hoomd can read it. second line specifies the first (and only) frame of the gsd file (this gsd . 
#third line  confirms frame. 
#fourth line shows us the type/name of particles (atoms/molecules) that hoomd recognizes
#fifth line shows us the snapshot at the specified timestep in the gsd file

#t = gsd.hoomd.open(name='/home/themotivation/Avo_atoms/airHCN.gsd', mode='rb')
#snap = t[0]
#snap.configuration.step
#print(snap.particles.types)
#print(snap.particles.position)
#snap.particles.particle_types
#snap.particles.position

In [4]:
#snap2 = hoomd.data.make_snapshot(N=19904, box=hoomd.data.boxdim(L=100), particle_types=['AR', 'C', 'H', 'N', 'O'])
#for x in range(0, 19904):
#    snap2.particles.position[x] = snap.particles.position[x]

#print(snap2.particles.position)

In [5]:
#print(snap2.particles.position)

In [6]:
#print(snap2.particles.velocity)

In [7]:
#hoomd.init.read_snapshot(snap2);

In [8]:
nl = hoomd.md.nlist.cell();

In [9]:
lj = hoomd.md.pair.lj(r_cut=2.5, nlist=nl);

In [10]:
lj.pair_coeff.set('N','N', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('N','0', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('N','AR', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('N','H', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('N','C', epsilon=1.0, sigma=1.0);

lj.pair_coeff.set('O','O', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('O','AR', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('O','C', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('O','H', epsilon=1.0, sigma=1.0);

lj.pair_coeff.set('AR','AR', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('AR','H', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('AR','N', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('AR','C', epsilon=1.0, sigma=1.0);

lj.pair_coeff.set('H','C', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('C','C', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('H','H', epsilon=1.0, sigma=1.0);
lj.pair_coeff.set('N','O', epsilon=1.0, sigma=1.0);

In [20]:
all = hoomd.group.all();

In [21]:

integrator = hoomd.md.integrate.npt(group=all, kT=2.49433795843, tau=138.08, tauP=1.0, P=2.0)

integrator.randomize_velocities(seed=42)

*Warning*: compute.thermo already specified for a group with name __npt_all
*Warning*: compute.thermo already specified for a group with name __npt_all


In [17]:
#hoomd.md.integrate.npt(all, kT=2.49433795843, tau=138.08, S=None, P=None, tauP=1, couple='xyz', x=True, y=True, z=True, xy=False, xz=False, yz=False, all=False, nph=False, rescale_all=None, gamma=None)

hoomd.dump.gsd("trajairHCN.gsd", period=2e3, group=all, overwrite=True);

In [18]:
hoomd.dump.gsd(filename="trajairHCN.gsd", period=100, group=all, overwrite=True, truncate=False, dynamic=['momentum']);

In [19]:
hoomd.run(1e4);

** starting run **
Time 00:02:24 | Step 20000 / 20000 | TPS 2421.48 | ETA 00:00:00
Average TPS: 2420.82
---------
-- Neighborlist stats:
0 normal updates / 0 forced updates / 0 dangerous updates
n_neigh_min: 0 / n_neigh_max: 0 / n_neigh_avg: 0
shortest rebuild period: 100
-- Cell list stats:
Dimension: 0, 0, 0
** run complete **


*Warning*: Starting a run without an integrator set*Warning*: You are running without an integrator


In [72]:
box.save("/home/themotivation/Avo_atoms/trajairHCN.gsd")
print("it worked!")

/home/themotivation/anaconda3/lib/python3.5/site-packages/mbuild/compound.py:1768: UserWarning: Guessing that "<AR pos=( 0.5265, 0.2604,-1.3727), 0 bonds, id: 140206773221920>" is element: "Ar"
  warn('Guessing that "{}" is element: "{}"'.format(atom, element))


it worked!


In [73]:
hoomd.data.gsd_snapshot("/home/themotivation/Avo_atoms/trajairHCN.gsd", frame=0)


In [75]:
print(snap.particles.velocity)
print(hoomd.get_step())

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
20000


In [3]:
snap2 = hoomd.data.make_snapshot(N=19904, box=hoomd.data.boxdim(L=100), particle_types=['AR', 'C', 'H', 'N', 'O'])
for x in range(0, 19904):
    snap3.particles.velocity[x] = "trajairHCN.gsd".particles.velocity[x]

NameError: name 'hoomd' is not defined